version: "3.7"
services:
    app:
        build:
            args:
                user: yommie
                uid: 1000
            context: ./docker/php
            dockerfile: Dockerfile
        image: yommie-airline-roster
        container_name: yommie-airline-roster-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - yommie-airline-roster-network

    nginx:
        image: nginx:1.17-alpine
        container_name: yommie-airline-roster-nginx
        restart: unless-stopped
        ports:
            - "8686:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - yommie-airline-roster-network

networks:
    yommie-airline-roster-network:
        driver: bridge
